include .env

setup:
	kubectl apply -f crds/.

run-operator:
	AZURE_CLIENT_ID=${AZURE_CLIENT_ID} \
	AZURE_TENANT_ID=${AZURE_TENANT_ID} \
	AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET} \
	SUBSCRIPTION_ID=${SUBSCRIPTION_ID} \
	RESOURCE_GROUP_NAME=${RESOURCE_GROUP_NAME} \
	DNS_ZONE_NAME=${DNS_ZONE_NAME} \
	APPGW_IP_ADDRESS=${APPGW_IP_ADDRESS} \
	kopf run -A --verbose appgw_external_dns/main.py

test:
	AZURE_CLIENT_ID=${AZURE_CLIENT_ID} \
	AZURE_TENANT_ID=${AZURE_TENANT_ID} \
	AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET} \
	SUBSCRIPTION_ID=${SUBSCRIPTION_ID} \
	RESOURCE_GROUP_NAME=${RESOURCE_GROUP_NAME} \
	DNS_ZONE_NAME=${DNS_ZONE_NAME} \
	APPGW_IP_ADDRESS=${APPGW_IP_ADDRESS} \
	../../bin/pytest -s
